"""Add Revision

Revision ID: 04cc169ec7ad
Revises: 07bae74d1f9e
Create Date: 2025-10-10 15:45:56.711596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04cc169ec7ad'
down_revision: Union[str, Sequence[str], None] = '07bae74d1f9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_annotations', sa.Column('revision', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('video_annotations', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('video_meta', sa.Column('revision', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('video_meta', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('videos', sa.Column('revision', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'revision')
    op.drop_column('video_meta', 'created_at')
    op.drop_column('video_meta', 'revision')
    op.drop_column('video_annotations', 'created_at')
    op.drop_column('video_annotations', 'revision')
    # ### end Alembic commands ###
