"""Reinit DB

Revision ID: 082fe47f3f54
Revises: 
Create Date: 2025-10-31 17:37:30.164796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '082fe47f3f54'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')

    op.create_table('authors',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v1mc()'), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('source', sa.Enum('tiktok', 'youtube_shorts', 'instagram_reels', 'other', name='video_source'), nullable=False),
    sa.Column('verified', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('followers', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_videos', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('is_reviewed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('ix_authors_created_at_desc', 'authors', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('challenge_pattern_group',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v1mc()'), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hashtags',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v1mc()'), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('source', sa.Enum('tiktok', 'youtube_shorts', 'instagram_reels', 'other', name='hashtag_source'), nullable=False),
    sa.Column('is_reviewed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hashtag_name_source', 'hashtags', ['name', 'source'], unique=True)
    op.create_table('scraper_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v1mc()'), nullable=False),
    sa.Column('scraper', sa.String(length=128), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_groups',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v1mc()'), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_searches',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v1mc()'), nullable=False),
    sa.Column('scraper', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=128), nullable=False),
    sa.Column('search_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ran_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('challenge_patterns',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v1mc()'), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=False),
    sa.Column('example', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['challenge_pattern_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenge_patterns_group_id'), 'challenge_patterns', ['group_id'], unique=False)
    op.create_table('challenges',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v1mc()'), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('name_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(name, ''))", persisted=True), nullable=False),
    sa.Column('pattern_used', sa.String(length=1024), nullable=False),
    sa.Column('translated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('categorized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('categorization_error', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['challenge_pattern_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_challenge_name_tsv', 'challenges', ['name_tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_challenges_group_id'), 'challenges', ['group_id'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v1mc()'), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['topic_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_group_id'), 'topics', ['group_id'], unique=False)
    op.create_table('videos',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v1mc()'), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('source', sa.Enum('tiktok', 'youtube_shorts', 'instagram_reels', 'other', name='video_source'), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('likes', sa.BigInteger(), server_default=sa.text('0'), nullable=True),
    sa.Column('views', sa.BigInteger(), server_default=sa.text('0'), nullable=True),
    sa.Column('comments', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('revision', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_videos_author_id'), 'videos', ['author_id'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v1mc()'), nullable=False),
    sa.Column('topic_group_id', sa.UUID(), nullable=False),
    sa.Column('pattern_group_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pattern_group_id'], ['challenge_pattern_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_group_id'], ['topic_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_pattern_group_id'), 'workflows', ['pattern_group_id'], unique=False)
    op.create_index(op.f('ix_workflows_topic_group_id'), 'workflows', ['topic_group_id'], unique=False)
    op.create_table('challenge_topics',
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('topic_id', 'challenge_id')
    )
    op.create_table('challenge_translations',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v1mc()'), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('lang', sa.String(length=2), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('value_tsv', postgresql.TSVECTOR(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenge_translations_challenge_id'), 'challenge_translations', ['challenge_id'], unique=False)
    op.create_table('challenge_videos',
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('challenge_id', 'video_id')
    )
    op.create_table('scraped_data',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v1mc()'), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraped_data_video_id'), 'scraped_data', ['video_id'], unique=False)
    op.create_table('topic_translations',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v1mc()'), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('lang', sa.String(length=2), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('value_tsv', postgresql.TSVECTOR(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_translations_topic_id'), 'topic_translations', ['topic_id'], unique=False)
    op.create_table('video_annotations',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v1mc()'), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('frame', 'frame_object', 'frame_action', 'frame_environment', 'frame_summary', 'frame_logo', 'label', 'synopsis', 'action', 'transcription', name='annotation_kind'), nullable=False),
    sa.Column('revision', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(value, ''))", persisted=True), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_video_annotations_value_tsv', 'video_annotations', ['value_tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_video_annotations_video_id'), 'video_annotations', ['video_id'], unique=False)
    op.create_table('video_hashtags',
    sa.Column('hashtag_id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hashtag_id', 'video_id')
    )
    op.create_table('video_meta',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v1mc()'), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('title', 'description', 'hashtag', 'frame_content_type', 'frame_style', 'frame_quality', 'topic', name='meta_source'), nullable=False),
    sa.Column('revision', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(value, ''))", persisted=True), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_video_meta_value_tsv', 'video_meta', ['value_tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_video_meta_video_id'), 'video_meta', ['video_id'], unique=False)
    op.create_table('video_processing_data',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v1mc()'), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_error', sa.Boolean(), nullable=True),
    sa.Column('categorized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('categorization_error', sa.Boolean(), nullable=True),
    sa.Column('challenges_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('challenges_creating_error', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_processing_data_video_id'), 'video_processing_data', ['video_id'], unique=False)
    op.create_index(op.f('ix_video_processing_data_workflow_id'), 'video_processing_data', ['workflow_id'], unique=False)
    op.create_table('video_searches',
    sa.Column('search_id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('is_new', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['topic_searches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('search_id', 'video_id')
    )
    op.create_table('video_topics',
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('topic_id', 'video_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_topics')
    op.drop_table('video_searches')
    op.drop_index(op.f('ix_video_processing_data_workflow_id'), table_name='video_processing_data')
    op.drop_index(op.f('ix_video_processing_data_video_id'), table_name='video_processing_data')
    op.drop_table('video_processing_data')
    op.drop_index(op.f('ix_video_meta_video_id'), table_name='video_meta')
    op.drop_index('ix_video_meta_value_tsv', table_name='video_meta', postgresql_using='gin')
    op.drop_table('video_meta')
    op.drop_table('video_hashtags')
    op.drop_index(op.f('ix_video_annotations_video_id'), table_name='video_annotations')
    op.drop_index('ix_video_annotations_value_tsv', table_name='video_annotations', postgresql_using='gin')
    op.drop_table('video_annotations')
    op.drop_index(op.f('ix_topic_translations_topic_id'), table_name='topic_translations')
    op.drop_table('topic_translations')
    op.drop_index(op.f('ix_scraped_data_video_id'), table_name='scraped_data')
    op.drop_table('scraped_data')
    op.drop_table('challenge_videos')
    op.drop_index(op.f('ix_challenge_translations_challenge_id'), table_name='challenge_translations')
    op.drop_table('challenge_translations')
    op.drop_table('challenge_topics')
    op.drop_index(op.f('ix_workflows_topic_group_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_pattern_group_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_videos_author_id'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_topics_group_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_challenges_group_id'), table_name='challenges')
    op.drop_index('ix_challenge_name_tsv', table_name='challenges', postgresql_using='gin')
    op.drop_table('challenges')
    op.drop_index(op.f('ix_challenge_patterns_group_id'), table_name='challenge_patterns')
    op.drop_table('challenge_patterns')
    op.drop_table('topic_searches')
    op.drop_table('topic_groups')
    op.drop_table('scraper_jobs')
    op.drop_index('ix_hashtag_name_source', table_name='hashtags')
    op.drop_table('hashtags')
    op.drop_table('challenge_pattern_group')
    op.drop_index('ix_authors_created_at_desc', table_name='authors')
    op.drop_table('authors')

    op.execute("DROP TYPE IF EXISTS video_source")
    op.execute("DROP TYPE IF EXISTS annotation_kind")
    op.execute("DROP TYPE IF EXISTS meta_source")
    # ### end Alembic commands ###
