"""Delete Jobs

Revision ID: 0837bc728f0d
Revises: 3734e51b410a
Create Date: 2025-10-30 14:01:11.130625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0837bc728f0d'
down_revision: Union[str, Sequence[str], None] = '3734e51b410a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('scraper_jobs_last_job_id_fkey'), 'scraper_jobs', type_='foreignkey')
    op.drop_column('scraper_jobs', 'last_job_id')
    op.drop_table('jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraper_jobs', sa.Column('last_job_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('scraper_jobs_last_job_id_fkey'), 'scraper_jobs', 'jobs', ['last_job_id'], ['id'], ondelete='SET NULL')
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v1mc()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('celery_job_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('processing_error', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('jobs_pkey'))
    )
    # ### end Alembic commands ###
