"""Add Enabled to ScrapedJob

Revision ID: 085c7e4127e9
Revises: a80f2eb2fc2e
Create Date: 2025-10-29 14:46:41.452586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '085c7e4127e9'
down_revision: Union[str, Sequence[str], None] = 'a80f2eb2fc2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraper_jobs', sa.Column('enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraper_jobs', 'enabled')
    # ### end Alembic commands ###
