"""Add Challenge Groups

Revision ID: 0bf843dd3543
Revises: da9abe97c336
Create Date: 2025-10-24 16:06:04.784669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0bf843dd3543'
down_revision: Union[str, Sequence[str], None] = 'da9abe97c336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge_groups',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v1mc()'), nullable=False),
    sa.Column('main_topic_id', sa.UUID(), nullable=False),
    sa.Column('additional_topic_id', sa.UUID(), nullable=False),
    sa.Column('last_challenges_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_batch', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['additional_topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['main_topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenge_groups_additional_topic_id'), 'challenge_groups', ['additional_topic_id'], unique=False)
    op.create_index(op.f('ix_challenge_groups_main_topic_id'), 'challenge_groups', ['main_topic_id'], unique=False)
    op.add_column('challenges', sa.Column('challenge_group_id', sa.UUID(), nullable=False))
    op.add_column('challenges', sa.Column('batch', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.drop_index(op.f('ix_challenges_topic_id'), table_name='challenges')
    op.create_index(op.f('ix_challenges_challenge_group_id'), 'challenges', ['challenge_group_id'], unique=False)
    op.drop_constraint(op.f('challenges_topic_id_fkey'), 'challenges', type_='foreignkey')
    op.create_foreign_key(None, 'challenges', 'challenge_groups', ['challenge_group_id'], ['id'], ondelete='CASCADE')
    op.drop_column('challenges', 'topic_id')
    op.drop_column('topics', 'last_challenges_created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('last_challenges_created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('challenges', sa.Column('topic_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'challenges', type_='foreignkey')
    op.create_foreign_key(op.f('challenges_topic_id_fkey'), 'challenges', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_challenges_challenge_group_id'), table_name='challenges')
    op.create_index(op.f('ix_challenges_topic_id'), 'challenges', ['topic_id'], unique=False)
    op.drop_column('challenges', 'batch')
    op.drop_column('challenges', 'challenge_group_id')
    op.drop_index(op.f('ix_challenge_groups_main_topic_id'), table_name='challenge_groups')
    op.drop_index(op.f('ix_challenge_groups_additional_topic_id'), table_name='challenge_groups')
    op.drop_table('challenge_groups')
    # ### end Alembic commands ###
