"""Add workflows

Revision ID: 1da107307868
Revises: a8f9a36ed5e0
Create Date: 2025-10-31 14:15:33.446955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1da107307868'
down_revision: Union[str, Sequence[str], None] = 'a8f9a36ed5e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v1mc()'), nullable=False),
    sa.Column('topic_group_id', sa.UUID(), nullable=False),
    sa.Column('pattern_group_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pattern_group_id'], ['challenge_pattern_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_group_id'], ['topic_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_pattern_group_id'), 'workflows', ['pattern_group_id'], unique=False)
    op.create_index(op.f('ix_workflows_topic_group_id'), 'workflows', ['topic_group_id'], unique=False)
    op.create_table('video_processing_data',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v1mc()'), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_error', sa.Boolean(), nullable=True),
    sa.Column('categorized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('categorization_error', sa.Boolean(), nullable=True),
    sa.Column('challenges_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('challenges_creating_error', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_processing_data_video_id'), 'video_processing_data', ['video_id'], unique=False)
    op.create_index(op.f('ix_video_processing_data_workflow_id'), 'video_processing_data', ['workflow_id'], unique=False)
    op.drop_column('videos', 'processed_at')
    op.drop_column('videos', 'categorization_error')
    op.drop_column('videos', 'challenges_creating_error')
    op.drop_column('videos', 'categorized_at')
    op.drop_column('videos', 'challenges_created_at')
    op.drop_column('videos', 'processing_error')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('processing_error', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('challenges_created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('categorized_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('challenges_creating_error', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('categorization_error', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_video_processing_data_workflow_id'), table_name='video_processing_data')
    op.drop_index(op.f('ix_video_processing_data_video_id'), table_name='video_processing_data')
    op.drop_table('video_processing_data')
    op.drop_index(op.f('ix_workflows_topic_group_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_pattern_group_id'), table_name='workflows')
    op.drop_table('workflows')
    # ### end Alembic commands ###
