"""Add VideoProcessing

Revision ID: 23a16bab5d3f
Revises: c64b0d4e8f0f
Create Date: 2025-10-20 08:45:21.461218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23a16bab5d3f'
down_revision: Union[str, Sequence[str], None] = 'c64b0d4e8f0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_processing',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v1mc()'), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('summarizing', 'categorization', name='video_processing_kind'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_error', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_processing_video_id'), 'video_processing', ['video_id'], unique=False)
    op.drop_column('videos', 'processing_error')
    op.drop_column('videos', 'processed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('processing_error', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_video_processing_video_id'), table_name='video_processing')
    op.drop_table('video_processing')

    op.execute("DROP TYPE IF EXISTS video_processing_kind")
    # ### end Alembic commands ###
