"""Add Challenge Topics

Revision ID: 2bb4cf532e35
Revises: 72ca67c8fdb6
Create Date: 2025-10-28 11:22:21.730163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bb4cf532e35'
down_revision: Union[str, Sequence[str], None] = '72ca67c8fdb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge_topics',
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('topic_id', 'challenge_id')
    )
    op.add_column('challenges', sa.Column('difficulty', sa.Float(), nullable=True))
    op.add_column('challenges', sa.Column('categorized_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('challenges', sa.Column('categorization_error', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenges', 'categorization_error')
    op.drop_column('challenges', 'categorized_at')
    op.drop_column('challenges', 'difficulty')
    op.drop_table('challenge_topics')
    # ### end Alembic commands ###
