"""Add Index for Author's Created At

Revision ID: 3734e51b410a
Revises: 085c7e4127e9
Create Date: 2025-10-29 15:49:04.589514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3734e51b410a'
down_revision: Union[str, Sequence[str], None] = '085c7e4127e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_authors_created_at_desc', 'authors', [sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_authors_created_at_desc', table_name='authors')
    # ### end Alembic commands ###
