"""Add Hashtags

Revision ID: 41b4c1f00eb6
Revises: 8c0830dcd97a
Create Date: 2025-10-20 15:54:13.844629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41b4c1f00eb6'
down_revision: Union[str, Sequence[str], None] = '8c0830dcd97a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashtags',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v1mc()'), nullable=False),
    sa.Column('source', sa.Enum('tiktok', 'youtube_shorts', 'instagram_reels', 'other', name='hashtag_source'), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('is_reviewed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hashtags_name'), 'hashtags', ['name'], unique=False)
    op.create_table('video_hashtags',
    sa.Column('hashtag_id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hashtag_id', 'video_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_hashtags')
    op.drop_index(op.f('ix_hashtags_name'), table_name='hashtags')
    op.drop_table('hashtags')
    # ### end Alembic commands ###
