"""Add TSVictor for Topics

Revision ID: 4b263f29ee8b
Revises: e4cb3d86db3e
Create Date: 2025-10-16 08:13:02.169425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b263f29ee8b'
down_revision: Union[str, Sequence[str], None] = 'e4cb3d86db3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('name_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(name, ''))", persisted=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'name_tsv')
    # ### end Alembic commands ###
