"""Initial

Revision ID: 5ecb8e2649ab
Revises: 
Create Date: 2025-10-08 17:02:50.210933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ecb8e2649ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v1mc()'), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('download_url', sa.String(), nullable=False),
    sa.Column('source', sa.Enum('TIKTOK', 'YOUTUBE_SHORTS', 'INSTAGRAM_REELS', 'OTHER', name='video_source'), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('author', sa.String(length=1024), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('duration_seconds >= 0', name='ck_video_duration_nonnegative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('video_annotations',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v1mc()'), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('FRAME', 'FRAME_OBJECT', 'FRAME_ACTION', 'FRAME_ENVIRONMENT', 'FRAME_SUMMARY', 'FRAME_LOGO', 'SUMMARY', 'SUMMARY_THEME', 'SUMMARY_VIDEO_TYPE', 'SUMMARY_SYNOPSIS', 'TRANSCRIPTION', name='annotation_kind'), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(value, ''))", persisted=True), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_video_annotations_value_tsv', 'video_annotations', ['value_tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_video_annotations_video_id'), 'video_annotations', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_annotations_video_id'), table_name='video_annotations')
    op.drop_index('ix_video_annotations_value_tsv', table_name='video_annotations', postgresql_using='gin')
    op.drop_table('video_annotations')
    op.drop_table('videos')
    op.execute("DROP TYPE IF EXISTS video_source")
    op.execute("DROP TYPE IF EXISTS annotation_kind")
    # ### end Alembic commands ###
