"""Add Challenge Patterns and Groups

Revision ID: 600261bb7f73
Revises: 7a49ca59227b
Create Date: 2025-10-27 10:49:25.924991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '600261bb7f73'
down_revision: Union[str, Sequence[str], None] = '7a49ca59227b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge_pattern_group',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v1mc()'), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('challenge_patterns',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v1mc()'), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=False),
    sa.Column('example', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['challenge_pattern_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenge_patterns_group_id'), 'challenge_patterns', ['group_id'], unique=False)
    op.add_column('challenges', sa.Column('group_id', sa.UUID(), nullable=False))
    op.add_column('challenges', sa.Column('name_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(name, ''))", persisted=True), nullable=False))
    op.add_column('challenges', sa.Column('pattern_used', sa.String(length=1024), nullable=False))
    op.add_column('challenges', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index('ix_challenge_name_tsv', 'challenges', ['name_tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_challenges_group_id'), 'challenges', ['group_id'], unique=False)
    op.create_foreign_key(None, 'challenges', 'challenge_pattern_group', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'challenges', type_='foreignkey')
    op.drop_index(op.f('ix_challenges_group_id'), table_name='challenges')
    op.drop_index('ix_challenge_name_tsv', table_name='challenges', postgresql_using='gin')
    op.drop_column('challenges', 'updated_at')
    op.drop_column('challenges', 'pattern_used')
    op.drop_column('challenges', 'name_tsv')
    op.drop_column('challenges', 'group_id')
    op.drop_index(op.f('ix_challenge_patterns_group_id'), table_name='challenge_patterns')
    op.drop_table('challenge_patterns')
    op.drop_table('challenge_pattern_group')
    # ### end Alembic commands ###
