"""Add Author and Video Details

Revision ID: 656ee387b2b5
Revises: ed1332498578
Create Date: 2025-10-13 08:52:56.214344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '656ee387b2b5'
down_revision: Union[str, Sequence[str], None] = 'ed1332498578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('verified', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.add_column('authors', sa.Column('followers', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('authors', sa.Column('total_videos', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('videos', sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('videos', sa.Column('likes', sa.BigInteger(), server_default=sa.text('0'), nullable=True))
    op.add_column('videos', sa.Column('views', sa.BigInteger(), server_default=sa.text('0'), nullable=True))
    op.add_column('videos', sa.Column('comments', sa.Integer(), server_default=sa.text('0'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'comments')
    op.drop_column('videos', 'views')
    op.drop_column('videos', 'likes')
    op.drop_column('videos', 'uploaded_at')
    op.drop_column('authors', 'total_videos')
    op.drop_column('authors', 'followers')
    op.drop_column('authors', 'verified')
    # ### end Alembic commands ###
