"""Delete video processing

Revision ID: 657d8e08a313
Revises: f4ed4cde4908
Create Date: 2025-10-22 14:39:44.454911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '657d8e08a313'
down_revision: Union[str, Sequence[str], None] = 'f4ed4cde4908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_processing_video_id'), table_name='video_processing')
    op.drop_table('video_processing')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_processing',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v1mc()'), autoincrement=False, nullable=False),
    sa.Column('video_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source', postgresql.ENUM('summarizing', 'categorization', name='video_processing_kind'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('processing_error', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_canceled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('video_processing_video_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('video_processing_pkey'))
    )
    op.create_index(op.f('ix_video_processing_video_id'), 'video_processing', ['video_id'], unique=False)
    # ### end Alembic commands ###
