"""Add challenges created at

Revision ID: 72ca67c8fdb6
Revises: 3c0014143fb5
Create Date: 2025-10-27 15:11:46.084442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72ca67c8fdb6'
down_revision: Union[str, Sequence[str], None] = '3c0014143fb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('challenges_created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('videos', sa.Column('challenges_creating_error', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'challenges_creating_error')
    op.drop_column('videos', 'challenges_created_at')
    # ### end Alembic commands ###
