"""Add Created at to ScrapedData

Revision ID: 76e1b7627487
Revises: 23a16bab5d3f
Create Date: 2025-10-20 10:33:43.362511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76e1b7627487'
down_revision: Union[str, Sequence[str], None] = '23a16bab5d3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraped_data', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraped_data', 'created_at')
    # ### end Alembic commands ###
