"""Delete additional topics and groups

Revision ID: 7a49ca59227b
Revises: 0bf843dd3543
Create Date: 2025-10-25 09:48:51.977842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a49ca59227b'
down_revision: Union[str, Sequence[str], None] = '0bf843dd3543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_challenges_challenge_group_id'), table_name='challenges')
    op.drop_constraint(op.f('challenges_challenge_group_id_fkey'), 'challenges', type_='foreignkey')
    op.drop_column('challenges', 'batch')
    op.drop_column('challenges', 'challenge_group_id')
    op.drop_index(op.f('ix_challenge_groups_additional_topic_id'), table_name='challenge_groups')
    op.drop_index(op.f('ix_challenge_groups_main_topic_id'), table_name='challenge_groups')
    op.drop_table('challenge_groups')
    op.drop_table('video_additional_topics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('challenge_group_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('challenges', sa.Column('batch', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('challenges_challenge_group_id_fkey'), 'challenges', 'challenge_groups', ['challenge_group_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_challenges_challenge_group_id'), 'challenges', ['challenge_group_id'], unique=False)
    op.create_table('video_additional_topics',
    sa.Column('video_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('main_topic_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('additional_topic_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint('main_topic_id <> additional_topic_id', name=op.f('chk_main_not_equal_additional')),
    sa.ForeignKeyConstraint(['additional_topic_id'], ['topics.id'], name=op.f('video_additional_topics_additional_topic_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['main_topic_id'], ['topics.id'], name=op.f('video_additional_topics_main_topic_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('video_additional_topics_video_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id', 'main_topic_id', 'additional_topic_id', name=op.f('video_additional_topics_pkey'))
    )
    op.create_table('challenge_groups',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v1mc()'), autoincrement=False, nullable=False),
    sa.Column('main_topic_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('additional_topic_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('last_challenges_created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_batch', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['additional_topic_id'], ['topics.id'], name=op.f('challenge_groups_additional_topic_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['main_topic_id'], ['topics.id'], name=op.f('challenge_groups_main_topic_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('challenge_groups_pkey'))
    )
    op.create_index(op.f('ix_challenge_groups_main_topic_id'), 'challenge_groups', ['main_topic_id'], unique=False)
    op.create_index(op.f('ix_challenge_groups_additional_topic_id'), 'challenge_groups', ['additional_topic_id'], unique=False)
    # ### end Alembic commands ###
