"""Add Challenges

Revision ID: 7eacd511f9fb
Revises: 8a8caacb4f37
Create Date: 2025-10-21 15:46:55.189909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7eacd511f9fb'
down_revision: Union[str, Sequence[str], None] = '8a8caacb4f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v1mc()'), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('translated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenges_topic_id'), 'challenges', ['topic_id'], unique=False)
    op.create_table('challenge_translations',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v1mc()'), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('lang', sa.String(length=2), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('value_tsv', postgresql.TSVECTOR(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenge_translations_challenge_id'), 'challenge_translations', ['challenge_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_challenge_translations_challenge_id'), table_name='challenge_translations')
    op.drop_table('challenge_translations')
    op.drop_index(op.f('ix_challenges_topic_id'), table_name='challenges')
    op.drop_table('challenges')
    # ### end Alembic commands ###
