"""Add is_revieved to Author

Revision ID: 8c0830dcd97a
Revises: c5d909a9bc93
Create Date: 2025-10-20 14:07:33.044293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c0830dcd97a'
down_revision: Union[str, Sequence[str], None] = 'c5d909a9bc93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('is_reviewed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'is_reviewed')
    # ### end Alembic commands ###
