"""Add Topic Groups

Revision ID: 8ebaca57a103
Revises: 0837bc728f0d
Create Date: 2025-10-30 15:45:29.290398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ebaca57a103'
down_revision: Union[str, Sequence[str], None] = '0837bc728f0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_groups',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v1mc()'), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('topics', sa.Column('group_id', sa.UUID(), nullable=False))
    op.add_column('topics', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_topics_group_id'), 'topics', ['group_id'], unique=False)
    op.create_foreign_key(None, 'topics', 'topic_groups', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.drop_index(op.f('ix_topics_group_id'), table_name='topics')
    op.drop_column('topics', 'updated_at')
    op.drop_column('topics', 'group_id')
    op.drop_table('topic_groups')
    # ### end Alembic commands ###
