"""Add Additional Topics

Revision ID: 929c1226709f
Revises: e415dd428813
Create Date: 2025-10-24 11:37:03.908187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '929c1226709f'
down_revision: Union[str, Sequence[str], None] = 'e415dd428813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_additional_topics',
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('main_topic_id', sa.UUID(), nullable=False),
    sa.Column('additional_topic_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('main_topic_id <> additional_topic_id', name='chk_main_not_equal_additional'),
    sa.ForeignKeyConstraint(['additional_topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['main_topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id', 'main_topic_id', 'additional_topic_id')
    )
    op.drop_index(op.f('ix_topic_name_tsv'), table_name='topics', postgresql_using='gin')
    op.drop_column('topics', 'name_tsv')
    op.drop_column('topics', 'translated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('translated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('topics', sa.Column('name_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english'::regconfig, (COALESCE(name, ''::character varying))::text)", persisted=True), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_topic_name_tsv'), 'topics', ['name_tsv'], unique=False, postgresql_using='gin')
    op.drop_table('video_additional_topics')
    # ### end Alembic commands ###
