"""Add Downloaded At

Revision ID: 97586abd0ac2
Revises: 082fe47f3f54
Create Date: 2025-11-03 10:04:45.081959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97586abd0ac2'
down_revision: Union[str, Sequence[str], None] = '082fe47f3f54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_processing_data', sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('video_processing_data', sa.Column('download_error', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_processing_data', 'download_error')
    op.drop_column('video_processing_data', 'downloaded_at')
    # ### end Alembic commands ###
