"""Add Topic Translations

Revision ID: aadca3d3ec59
Revises: f285d0139cca
Create Date: 2025-10-23 13:13:24.635593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aadca3d3ec59'
down_revision: Union[str, Sequence[str], None] = 'f285d0139cca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_translations',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v1mc()'), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('lang', sa.String(length=2), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('value_tsv', postgresql.TSVECTOR(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_translations_topic_id'), 'topic_translations', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_translations_topic_id'), table_name='topic_translations')
    op.drop_table('topic_translations')
    # ### end Alembic commands ###
