"""Add is_canceled to VideoProcessing

Revision ID: c5d909a9bc93
Revises: 76e1b7627487
Create Date: 2025-10-20 11:35:31.269887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5d909a9bc93'
down_revision: Union[str, Sequence[str], None] = '76e1b7627487'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_processing', sa.Column('is_canceled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_processing', 'is_canceled')
    # ### end Alembic commands ###
