"""Add Index for topic and Remove topic_id from searches

Revision ID: c64b0d4e8f0f
Revises: 337e4b47bdc8
Create Date: 2025-10-19 11:33:13.670179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c64b0d4e8f0f'
down_revision: Union[str, Sequence[str], None] = '337e4b47bdc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_searches_topic_id'), table_name='topic_searches')
    op.drop_constraint(op.f('topic_searches_topic_id_fkey'), 'topic_searches', type_='foreignkey')
    op.drop_column('topic_searches', 'topic_id')
    op.create_index('ix_topic_name_tsv', 'topics', ['name_tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_topic_name_tsv', table_name='topics', postgresql_using='gin')
    op.add_column('topic_searches', sa.Column('topic_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('topic_searches_topic_id_fkey'), 'topic_searches', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_topic_searches_topic_id'), 'topic_searches', ['topic_id'], unique=False)
    # ### end Alembic commands ###
