"""Add Processed At and Categorized At

Revision ID: cc94d560ae2b
Revises: 657d8e08a313
Create Date: 2025-10-23 07:53:10.634689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc94d560ae2b'
down_revision: Union[str, Sequence[str], None] = '657d8e08a313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('videos', sa.Column('processing_error', sa.Boolean(), nullable=True))
    op.add_column('videos', sa.Column('categorized_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('videos', sa.Column('categorization_error', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'categorization_error')
    op.drop_column('videos', 'categorized_at')
    op.drop_column('videos', 'processing_error')
    op.drop_column('videos', 'processed_at')
    # ### end Alembic commands ###
