"""Add Translated At to Topic

Revision ID: e415dd428813
Revises: aadca3d3ec59
Create Date: 2025-10-23 13:44:39.970658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e415dd428813'
down_revision: Union[str, Sequence[str], None] = 'aadca3d3ec59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('translated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'translated_at')
    # ### end Alembic commands ###
