"""init

Revision ID: fb0d9cb0f6b7
Revises: 
Create Date: 2025-10-09 11:04:04.010694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb0d9cb0f6b7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.create_table('videos',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v1mc()'), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('source', sa.Enum('TIKTOK', 'YOUTUBE_SHORTS', 'INSTAGRAM_REELS', 'OTHER', name='video_source'), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('scraped_data',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v1mc()'), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraped_data_video_id'), 'scraped_data', ['video_id'], unique=False)
    op.create_table('video_annotations',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v1mc()'), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('FRAME', 'FRAME_OBJECT', 'FRAME_ACTION', 'FRAME_ENVIRONMENT', 'FRAME_SUMMARY', 'FRAME_LOGO', 'SUMMARY', 'SUMMARY_SYNOPSIS', 'TRANSCRIPTION', name='annotation_kind'), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(value, ''))", persisted=True), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_video_annotations_value_tsv', 'video_annotations', ['value_tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_video_annotations_video_id'), 'video_annotations', ['video_id'], unique=False)
    op.create_table('video_meta',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v1mc()'), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('POST', 'POST_AUTHOR', 'HASHTAG', 'FRAME_CONTENT_TYPE', 'FRAME_STYLE', 'FRAME_QUALITY', 'SUMMARY', 'SUMMARY_VIDEO_TYPE', name='meta_source'), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(value, ''))", persisted=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_video_meta_value_tsv', 'video_meta', ['value_tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_video_meta_video_id'), 'video_meta', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_meta_video_id'), table_name='video_meta')
    op.drop_index('ix_video_meta_value_tsv', table_name='video_meta', postgresql_using='gin')
    op.drop_table('video_meta')
    op.drop_index(op.f('ix_video_annotations_video_id'), table_name='video_annotations')
    op.drop_index('ix_video_annotations_value_tsv', table_name='video_annotations', postgresql_using='gin')
    op.drop_table('video_annotations')
    op.drop_index(op.f('ix_scraped_data_video_id'), table_name='scraped_data')
    op.drop_table('scraped_data')
    op.drop_table('videos')
    op.execute("DROP TYPE IF EXISTS video_source")
    op.execute("DROP TYPE IF EXISTS annotation_kind")
    op.execute("DROP TYPE IF EXISTS meta_source")
    # ### end Alembic commands ###
